package greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STUDENT".
 */
@Entity
public class Student {

    @Id
    private Long id;

    @NotNull
    private String sName;
    private String sAge;
    private String sSex;
    private String sClass;

    @Generated(hash = 1556870573)
    public Student() {
    }

    public Student(Long id) {
        this.id = id;
    }

    @Generated(hash = 1604919357)
    public Student(Long id, @NotNull String sName, String sAge, String sSex, String sClass) {
        this.id = id;
        this.sName = sName;
        this.sAge = sAge;
        this.sSex = sSex;
        this.sClass = sClass;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getSName() {
        return sName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSName(@NotNull String sName) {
        this.sName = sName;
    }

    public String getSAge() {
        return sAge;
    }

    public void setSAge(String sAge) {
        this.sAge = sAge;
    }

    public String getSSex() {
        return sSex;
    }

    public void setSSex(String sSex) {
        this.sSex = sSex;
    }

    public String getSClass() {
        return sClass;
    }

    public void setSClass(String sClass) {
        this.sClass = sClass;
    }

}
