package com.example.ormtest.realm;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.RealmClass;

/**
 * User: wanglg
 * Date: 2016-08-01
 * Time: 15:31
 * FIXME
 */
@RealmClass
public class UserRealm extends RealmObject {
    private String name;
    private int age;

    @Ignore
    private int sessionId;

    // Standard getters & setters generated by your IDE…
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public int getSessionId() {
        return sessionId;
    }

    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }
}
